---
title: "EDA for nfl_yards"
author: "Kory D. Johnson"
date: 'Last Compiled `r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    code_folding: show
    highlight: tango
    number_sections: yes
    theme: cosmo
    toc: yes
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = TRUE,
               collapse = FALSE,
               comment = "",
               strip.white = TRUE,
               warning = FALSE,
               message = FALSE,
               out.width = "70%",
               fig.align = "center")
```

## Topic

Defining features. Here because faster to iterate than python.

## Set Up  {.tabset .tabset-fade}

### Packages/Files {-}

```{r}
library(tidyverse)
library(magrittr)
```

### Load Data {-}

```{r, cache=T}
loadData <- function(fileName = "train.csv", ...) {
  file = paste("../input", fileName, sep="/")
  data.table::fread(file, ...) %>% 
    as_tibble()
}
df = loadData("trainClean.csv")
```

# Features w/o Players

## Distance to Goal

```{r}
df = df %>% 
  mutate(YardsToGoal = YardLine + (100-2*YardLine)*(PossessionTeam==FieldPosition))
df %>% 
  distinct(PlayId, .keep_all=T) %>% 
  ggplot(aes(x=YardsToGoal)) +
  geom_histogram()
```

Why is 75 ish so much more common?

## Line of Scrimmage
```{r}
df %<>% 
  mutate(LOS_Side = ifelse((PlayDirection=="right" & PossessionTeam==FieldPosition) |
                             (PlayDirection=="left" & PossessionTeam!=FieldPosition),
                           "left", "right"),
         LineOfScrimmage = ifelse(LOS_Side=="left", YardLine+10, 110-YardLine))
dfLOS = df %>% 
  group_by(PlayId) %>% 
  summarise(DistanceToLOS = mean(abs(X-LineOfScrimmage))) %>% 
  arrange(desc(DistanceToLOS))
ggplot(dfLOS) +
  geom_histogram(aes(DistanceToLOS))
longDist = dfLOS %>% 
  pull(PlayId) %>% 
  head()
index=1
plotPlay(filter(df, PlayId==longDist[index]), "DistanceToLOS", dfLOS[1, "DistanceToLOS"])
```

Checking python data
```{r}
dfPy = loadData("trainClean_py.csv") %>% 
  arrange(desc(DistanceToLOS))
ggplot(dfPy) +
  geom_histogram(aes(DistanceToLOS))
longDist = dfPy %>% 
  pull(PlayId) %>% 
  head()
index=1
plotPlay(filter(df, PlayId==longDist[index]), "DistanceToLOS", dfPy[1, "DistanceToLOS"])
dfPy %>% 
  filter(PlayId==longDist[index]) %>% 
  select(PossessionTeam, FieldPosition, HomeTeamAbbr, VisitorTeamAbbr, DistanceToGoal, DistanceToLOS)
```

