---
title: "Notes on "
author: "Kory D. Johnson"
date: 'Last Compiled `r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
     code_folding: show
    highlight: tango
    number_sections: yes
    theme: cosmo
    toc: yes
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = TRUE,
               collapse = FALSE,
               comment = "",
               strip.white = TRUE,
               warning = FALSE,
               message = FALSE,
               out.width = "70%",
               fig.align = "center")
```

## Topic

This file 

## Set Up  {.tabset .tabset-fade}

### Packages/Files {-}

```{r}
library(tidyverse)
library(magrittr)
```

### Load Data {-}

```{r, cache=T}
loadData <- function(fileName = "train.csv", ...) {
  file = paste("../input", fileName, sep="/")
  data.table::fread(file, ...) %>% 
    as_tibble()
}
df = loadData("trainClean.csv")
df = loadData()
dfTest = loadData("test.csv")
```

# Missing Values

```{r}
df %>% 
  summarise_all(function(col) sum(is.na(col)))
```


# Compare Features to Test Set

```{r}
compareTest = function(dfTrain, dfTest, feature, year=NULL) {
  dfTr = dfTrain %>% 
    filter(NflId==NflIdRusher)
  if (!is.null(year)) {
    dfTr %<>% 
      filter(str_detect(GameId, paste0("^", year, ".*")))
  }
  dfTe = dfTest %>% 
    filter(NflId==NflIdRusher)

  ggplot() + 
    geom_density(data=dfTr, aes(!!sym(feature), color=paste("train", year))) +
    geom_density(data=dfTe, aes(!!sym(feature), color="test")) +
    labs(color = "Data Set")
}
compareTest(df, dfTest, "A", 2017)
```

# Check Raw Data

strange observation
```{r}
filter(df, PlayId=="20181007032152", NflId==NflIdRusher)
```

# Heteroskedasticity

Look at variability of yards in each category
```{r}
df %<>%
  mutate(YardsCategory = cut(Yards, breaks = c(-Inf, 0, 3, 6, Inf), 
             labels=c("bad", "short", "med", "long")))
ggplot(df) + 
  geom_histogram(aes(Yards), binwidth=1) + 
  facet_wrap(~YardsCategory, scales="free_x")
```

# EDA {.tabset .tabset-fade}

Looking at subset of Data
```{r}
ggplot(dfSub, aes(Distance, Yards)) +
  geom_jitter() +
  geom_smooth(se=F) +
  facet_wrap(~factor(Down))
```

## Sub1 {-}

## Sub2 {-}