---
title: "Plotting Plays, Python Data (Standardized Direction and Location)"
author: "Kory D. Johnson"
date: 'Last Compiled `r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    code_folding: show
    highlight: tango
    number_sections: yes
    theme: cosmo
    toc: yes
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = TRUE,
               collapse = FALSE,
               comment = "",
               strip.white = TRUE,
               warning = FALSE,
               message = FALSE,
               out.width = "70%",
               fig.align = "center")
```

## Topic

This file 

## Set Up  {.tabset .tabset-fade}

### Packages/Files {-}

```{r}
library(tidyverse)
library(magrittr)
library(ggforce)
```

### Load Data {-}

```{r, cache=T}
loadData <- function(fileName = "train.csv", ...) {
  file = paste("../input", fileName, sep="/")
  data.table::fread(file, ...) %>% 
    as_tibble()
}
df = loadData("trainClean_py.csv")
df %<>%
  mutate(
    X_end = S*cos((90-Dir)*pi/180) + X, 
    Y_end = S*sin((90-Dir)*pi/180) + Y
  )
dfFeatures = loadData("features_py.csv")
```

# Plot code from rescale file

Taken from https://www.kaggle.com/statsbymichaellopez/nfl-tracking-wrangling-voronoi-and-sonars#Dealing-with-player-tracking-data

```{r}
options(repr.plot.width=10, repr.plot.height=6)
samp_play <- "20170910001102"
plotPlay = function(dfPlay, features=NULL, run=F) {
  rusherSpeed = dfPlay %>% 
    filter(NflId == NflIdRusher) %>% 
    pull(S)
  p = dfPlay %>% 
    ggplot(aes(X, Y, color = OnOffense))  + 
    geom_point(size = 2) + 
    geom_segment(aes(x = X, y = Y, xend = X_end, yend = Y_end), 
                 arrow = arrow(length = unit(.5,"cm"))) + 
    geom_point(data = filter(dfPlay, NflId == NflIdRusher), 
               pch=21, size = 1.5, fill = "black") +
    # geom_point(data = filter(dfPlay, Position == "QB"), size = 2, fill = "blue") +
    scale_colour_brewer(palette = "Set2")+ 
    scale_fill_brewer(palette = "Set2")+ 
    # geom_vline(aes(xintercept=0), color="grey") +
    # geom_vline(aes(xintercept=10), color="grey") +
    geom_vline(aes(xintercept = LineOfScrimmage), colour = "black", lty = 2) + 
    coord_cartesian(ylim=c(0,160/3), expand=F) + #xlim = c(-10,110), 
    labs(
      x = "Distance from offensive team's own end zone", 
      y = "Y", 
      title = paste0("PlayId ", pull(dfPlay, PlayId)), 
      subtitle = paste("Yards", dfPlay$Yards, "; ", "Down", dfPlay$Down)
    ) + 
    theme_bw(14) + 
    theme(panel.grid.minor = element_blank(), panel.grid.major.y =element_blank())
  if (run && !is.null(features)) {
    dfC = circleDF(c(features$LineOfScrimmage, features$Rusher_Gap_Center),
                   features$Rusher_Gap_Radius*rusherSpeed)
    p + 
      geom_path(data = dfC, aes(x, y), color="gold") +
      labs(subtitle = paste("Yards", dfPlay$Yards, "; ", "Down", dfPlay$Down, "; ",
                            "NPlayers", features$Rusher_Gap_NPlayers, "; ",
                            "OpenSize", round(features$Rusher_Gap_OpenSize, 2)))
  } else {
    p
  }
}
circleDF = function(center = c(0,0), r = 1, npoints = 100){
    tt <- seq(0, 2*pi, length.out = npoints)
    xx <- center[1] + r * cos(tt)
    yy <- center[2] + r * sin(tt)
    return(data.frame(x = xx, y = yy))
}
dfPlay = filter(df, PlayId == samp_play)
features = filter(dfFeatures, PlayId == samp_play)
plotPlay(dfPlay, features, run=T)
```


# Looking at Plays

First, categorize runs: long, medium, short, bad
```{r}
ggplot(df) +
  geom_density(aes(Yards))
summary(df$Yards)
df %<>%
  mutate(YardsCategory = cut(Yards, breaks = c(-Inf, 0, 3, 6, Inf), 
             labels=c("bad", "short", "med", "long")))
table(df$YardsCategory)
PlayId_long = df %>% 
  filter(YardsCategory == "long") %>% 
  pull(PlayId)
PlayId_med = df %>% 
  filter(YardsCategory == "med") %>% 
  pull(PlayId)
PlayId_short = df %>% 
  filter(YardsCategory == "short") %>% 
  pull(PlayId)
PlayId_bad = df %>% 
  filter(YardsCategory == "bad") %>% 
  pull(PlayId)
```

Plot several runs from vector of ids
```{r}
plotPlays = function(ids, n=5) {
  for (index in sample.int(length(ids), min(n, length(ids)))) {
    id = ids[index]
    dfPlay = filter(df, PlayId == id)
    features = filter(dfFeatures, PlayId == id)
    p = plotPlay(dfPlay, features, run=T)
    print(p)
  }
}
```

## Long Runs
```{r}
plotPlays(PlayId_long)
"20181007032152"
```

strange play
```{r}
plotPlays("20171210021098")
filter(df, PlayId=="20181007032152")
```

## Medium Runs
```{r}
plotPlays(PlayId_med)
```

## Short Runs
```{r}
plotPlays(PlayId_short)
```

## Bad Runs
```{r}
plotPlays(PlayId_bad)
```

## To Edge

```{r}
edgePlays = dfFeatures %>% 
  filter(Rusher_Gap_ToEdge == 1) %>% 
  pull(PlayId)
plotPlays(edgePlays)
```